#
# Freescale DataPath Acceleration Architecture Gen2 (DPAA2) drivers
#

obj-$(CONFIG_FSL_DPAA2_ETH)		+= ethernet/
obj-$(CONFIG_FSL_DPAA2_PTP_CLOCK)	+= rtc/
obj-$(CONFIG_FSL_DPAA2_MAC)	+= mac/
obj-$(CONFIG_FSL_DPAA2_EVB)	+= evb/
obj-$(CONFIG_FSL_DPAA2_ETHSW)	+= ethsw/
